name = "FlowFreeSolver"
uuid = "147e91f2-30fd-4abb-a95a-c9360eed14d4"
authors = ["Austin Schaffer <schaffer.austin.t@gmail.com>"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
