[package]
name = "day_04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unused_imports = "allow"
dead_code = "allow"

[dependencies]
lazy_static = "1.4.0"
regex = "1.10.2"
