# Generated by Django 4.2 on 2023-04-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicefirmwareupdateevent',
            index=models.Index(fields=['device_id', 'timestamp', 'version'], name='dev_fw_update_event_idx'),
        ),
    ]
