# Generated by Django 4.2 on 2023-04-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicefirmwareupdateevent_dev_fw_update_event_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
