# Generated by Django 4.2 on 2023-04-25 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.BinaryField(editable=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectmembershipapikey',
            name='project_membership_id',
        ),
        migrations.DeleteModel(
            name='ProjectMembership',
        ),
        migrations.DeleteModel(
            name='ProjectMembershipApiKey',
        ),
    ]
