# Generated by Django 4.2 on 2023-04-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_projectapikey_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='devicefirmwareupdateevent',
            name='dev_fw_update_event_idx',
        ),
        migrations.AddIndex(
            model_name='devicefirmwareupdateevent',
            index=models.Index(fields=['device_id'], name='device_id_idx'),
        ),
    ]
